# Site settings
title: Raghav Rakesh
description: Ph.D. Candidate in Economics, Michigan State University
url: 'https://raghavrakesh.github.io'
baseurl: ""
google_analytics: 'G-2EC3BX97V6'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Raghav Rakesh'
  email: rakeshra@msu.edu

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
